from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class PredictionHistory(db.Model):
    __tablename__ = 'prediction_history'
    
    id = db.Column(db.Integer, primary_key=True)
    subdivision = db.Column(db.String(100), nullable=False)
    year = db.Column(db.Integer, nullable=False)
    predicted_annual = db.Column(db.Float, nullable=False)
    predicted_monsoon = db.Column(db.Float, nullable=False)
    confidence = db.Column(db.Float, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        return {
            'id': self.id,
            'subdivision': self.subdivision,
            'year': self.year,
            'predictedAnnual': self.predicted_annual,
            'predictedMonsoon': self.predicted_monsoon,
            'confidence': self.confidence,
            'created_at': self.created_at.isoformat()
        }

def init_db(app):
    """Initialize database for the Flask app"""
    # SQLite Database stored in the local instance folder generated by Flask
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///rainfall.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
    
    with app.app_context():
        db.create_all()
