from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import os
from datetime import datetime

def generate_prediction_pdf(prediction_data, output_path):
    """
    Generates a PDF report for a rainfall prediction.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title = Paragraph("Rainfall Prediction Report", styles['Title'])
    story.append(title)
    story.append(Spacer(1, 12))

    # Meta Information
    meta_info = f"""
    <b>Report Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}<br/>
    <b>Subdivision:</b> {prediction_data['metadata']['subdivision']}<br/>
    <b>Year:</b> {prediction_data['metadata']['year']}<br/>
    <b>Confidence Score:</b> {prediction_data['confidence']}%
    """
    story.append(Paragraph(meta_info, styles['Normal']))
    story.append(Spacer(1, 12))

    # Summary
    summary = f"""
    The predicted annual rainfall for <b>{prediction_data['metadata']['subdivision']}</b> in the year <b>{prediction_data['metadata']['year']}</b> is approximately <b>{prediction_data['predictedAnnual']} mm</b>. 
    The monsoon season alone is expected to bring around <b>{prediction_data['predictedMonsoon']} mm</b>.
    """
    story.append(Paragraph(summary, styles['Normal']))
    story.append(Spacer(1, 20))

    # Seasonal Breakdown Table
    story.append(Paragraph("<b>Seasonal Breakdown:</b>", styles['Heading2']))
    story.append(Spacer(1, 10))

    table_data = [["Season", "Predicted Rainfall (mm)"]]
    for item in prediction_data['seasonalData']:
        table_data.append([item['season'], str(item['rainfall'])])

    table = Table(table_data, colWidths=[200, 150])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(table)
    story.append(Spacer(1, 30))
    
    footer = Paragraph("<i>Generated by the Rainfall Prediction System. Powered by Machine Learning.</i>", styles['Normal'])
    story.append(footer)

    doc.build(story)
    return output_path
